import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavbarMenuItems from "@/components/Navbar";

const inter = Poppins({ subsets: ["latin"] ,weight: ['100','300','400','500','700','900']});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <NavbarMenuItems/>
        {children}
      </body>
    </html>
  );
}
